version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports: # Uncomment only one line
    # Exposed to localhost only
    - "127.0.0.1:4466:4466"
    # Exposed externally, make sure you have firewall or managementApiSecret implemented
    #- "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  grafana:
    image: grafana/grafana:6.3.2
    restart: always
    ports:
    - 80:3000
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    - grafana_data:/var/lib/grafana
    env_file:
    - ./grafana/config.monitoring
  postgres:
    image: postgres
    restart: always
    expose:
    - 5432
    ports:
    - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  grafana_data: